CREATE DATABASE FPro;
CREATE TABLE Users (
	memberID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
)

CREATE TABLE Session(
	id INT(6),
	sessionID(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE Messages(
	senderID INT(6),
	receiverID INT(6),
	message VARCHAR(255),
	c INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	PRIMARY KEY(senderID,receiverID)
)
	